"""Layer 3: compile the figure/table fragments with Tectonic.

Each generator (scripts/fig_<name>.py) writes an \\input-able LaTeX fragment
to output/figures/tex/<name>.tex. This script wraps every fragment in the
paper's preamble (scripts/fig_preamble.tex) and compiles:

  output/figures/pdf/<name>.pdf   one page per figure/table (preview)
  output/figures/figures.pdf      all of them, opening with a list of figures
                                  and a list of tables, one artifact per page

Figures and tables carry their paper numbers (`number` in the FIGURES registry
of replicate.py: Figure 7, Table B1, ...), not the order of the document.
Web-appendix items are marked as such.

Requires `tectonic` on PATH (pinned in mise.toml). Tectonic reruns the engine
until cross-references settle, which the lists and the pgfplots
legend-to-name legends need.
"""
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from replicate import FIGURES, REPO, BUNDLE_PATH  # noqa: E402

TEX_DIR = os.path.join("output", "figures", "tex")
PDF_DIR = os.path.join("output", "figures", "pdf")
COMBINED = os.path.join("output", "figures", "figures.pdf")
PREAMBLE = os.path.join(REPO, "scripts", "fig_preamble.tex")

# Build-wrapper mechanics the paper preamble lacks: \includestandalone support
# and the pgfplots compat level the generators were written against.
PREAMBLE_EXTRAS = (
    "\n% --- added by scripts/fig_compile.py (not in the paper preamble) ---\n"
    "\\usepackage{standalone}\n"
    "\\pgfplotsset{compat=1.17}\n"
)

SECTIONS = [(("sample_vs_population", "ivi_binding_function"), "Indirect variational inference"),
            (("ar1n_",), "AR(1) linear-Gaussian model"),
            (("hockeystick_",), "Nonlinear hockey-stick model"),
            (("hetero_scale_",), "Heterogeneity model"),
            (("psid_",), "PSID application"),
            (("computational_settings_table",), "Computational appendix")]


def head():
    with open(PREAMBLE, encoding="utf-8") as f:
        return f.read().rstrip() + "\n" + PREAMBLE_EXTRAS


def tex_escape(s):
    return s.replace("\\", r"\textbackslash{}").replace("_", r"\_").replace("&", r"\&")


def kind(fig):
    return "figure" if fig["number"].startswith("fig") else "table"


def label(fig):
    """'Figure 7', 'Table B1' -- the paper's number."""
    return ("Figure " if kind(fig) == "figure" else "Table ") + fig["number"][3:]


def numbering(fig):
    """Make the fragment's \\caption carry the paper number."""
    return "\\renewcommand{\\the" + kind(fig) + "}{" + fig["number"][3:] + "}"


def section(fig):
    return next((t for prefixes, t in SECTIONS if fig["name"].startswith(prefixes)), "Other")


def compile_tex(name, tex_dir=TEX_DIR, pdf_dir=PDF_DIR):
    """tectonic <tex_dir>/<name>.tex -> <pdf_dir>/<name>.pdf; returns the pdf path."""
    exe = shutil.which("tectonic")
    if not exe:
        sys.exit("tectonic not found on PATH: run `mise install` (see mise.toml) "
                 "or install Tectonic, then retry")
    os.makedirs(pdf_dir, exist_ok=True)
    r = subprocess.run([exe, "--keep-logs", "--outdir", os.path.abspath(pdf_dir), f"{name}.tex"],
                       cwd=tex_dir, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    pdf = os.path.join(pdf_dir, f"{name}.pdf")
    if r.returncode != 0 or not os.path.exists(pdf):
        sys.stdout.write(r.stdout[-4000:])
        sys.exit(f"tectonic failed on {name}.tex")
    return pdf


def check_fragments():
    missing = [f["name"] for f in FIGURES
               if not os.path.exists(os.path.join(TEX_DIR, f["name"] + ".tex"))]
    if missing:
        sys.exit(f"missing fragments (run the fig-* tasks first): {missing}")


def main():
    check_fragments()
    preamble = head()

    # One preview page per artifact.
    for fig in FIGURES:
        wrapper = f"{fig['name']}.preview"
        with open(os.path.join(TEX_DIR, wrapper + ".tex"), "w", encoding="utf-8") as f:
            f.write(preamble + "\\begin{document}\n\\centering\n" + numbering(fig) + "\n"
                    f"\\input{{{fig['name']}.tex}}\n\\end{{document}}\n")
        pdf = compile_tex(wrapper)
        os.replace(pdf, os.path.join(PDF_DIR, f"{fig['name']}.pdf"))
        print(f"  compiled pdf/{fig['name']}.pdf  ({label(fig)})")

    # Combined document: lists of figures and tables on the first page, then
    # one artifact per page under its section, each labelled with the
    # generator and input bundle(s) that produced it.
    body = [preamble + "\\begin{document}",
            "\\begin{center}{\\Large Figures and tables}\\\\[0.5em]"
            "{\\small generated by \\texttt{python replicate.py run -{}-layer 3}}\\end{center}",
            "\\listoffigures", "\\listoftables", "\\clearpage"]
    current = None
    for fig in FIGURES:
        sec = section(fig)
        if sec != current:
            body.append(f"\\section*{{{sec}}}")
            current = sec
        inputs = ([fig["bundle"]] if fig["bundle"] else []) + list(fig.get("reads", []))
        source = ", ".join("\\texttt{" + tex_escape(BUNDLE_PATH[b]) + "}" for b in inputs) \
            or "fixed content"
        body.append("\\noindent{\\footnotesize " + label(fig)
                    + (" (web appendix)" if fig.get("online") else "")
                    + ": \\texttt{scripts/fig\\_" + tex_escape(fig["name"]) + ".py} $\\leftarrow$ "
                    + source + "}\\par")
        body.append(numbering(fig))
        body.append("\\begin{center}\\input{" + fig["name"] + ".tex}\\end{center}")
        body.append("\\clearpage")
    body.append("\\end{document}")
    with open(os.path.join(TEX_DIR, "figures.tex"), "w", encoding="utf-8") as f:
        f.write("\n".join(body) + "\n")
    pdf = compile_tex("figures")
    os.replace(pdf, COMBINED)
    print(f"  compiled {COMBINED}  ({len(FIGURES)} artifacts)")


if __name__ == "__main__":
    main()
